### ISSUE TITLE
Data de início

### ISSUE THREAD

**Issue by Marlysson** [ednilsonamaral/webschool-curso-vuejs#1]
Tem data de início já programada?

**Comment by ednilsonamaral** [comment]
Opa, belezura, @Marlysson? Então, estou fechando a ementa nos próximos dias e começar a gravas as aulas e disponibilizar para vocês.

O repositório oficial do curso é [esse](https://github.com/Webschool-io/Curso-VueJS).

**Comment by Marlysson** [comment]
Opa.. Show de bola.. Acompanhar pra fazer ele ..
